export const adminNavigation = [
  ['', 'Mission Control', 'layout-dashboard', ''],
  ['profile', 'Profilul meu', 'user', ''],
  ['inbox', 'Inbox notificări', 'bell', ''],
  ['tasks', 'Task Hub', 'list-todo', 'canManageTasks'],
  ['content', 'Content Studio', 'file-pen-line', 'canEditDocs'],
  ['media', 'Media Vault', 'folder', 'canManageMedia'],
  ['health', 'Doc Health', 'activity', 'canManageHealth'],
  ['search-analytics', 'Search Analytics', 'search', 'canViewAnalytics'],
  ['ai-analytics', 'AI Analytics', 'sparkles', 'canViewAiStats'],
  ['database', 'Database', 'database', 'canManageDb'],
  ['backups', 'Snapshot Vault', 'archive', 'canManageSnapshots'],
  ['team', 'Echipă și permisiuni', 'users', 'canManageTeam'],
  ['security', 'Securitate', 'shield-check', 'canManageSecurity'],
  ['api-keys', 'API Keys', 'key-round', 'canManageApiKeys'],
  ['audit', 'Audit Ledger', 'scroll-text', 'canViewAudit'],
  ['webhooks', 'Webhooks', 'webhook', 'canManageWebhooks'],
  ['settings', 'Setări platformă', 'sliders-horizontal', 'canManageSettings'],
  ['gitops', 'GitOps', 'git-branch', 'root'],
  ['discord-bot', 'Discord Bot', 'bot', 'canManageDiscordBot'],
  ['discord-bot/modules', 'Module Discord', 'blocks', 'canManageDiscordBot'],
  ['discord-bot/role-trackers', 'Role Trackers', 'radar', 'canManageDiscordBot'],
  ['discord-bot/staff', 'Discord Staff', 'users-round', 'canManageDiscordBot'],
  ['discord-bot/tickets', 'Tickete', 'tickets', 'canManageDiscordBot'],
  ['discord-bot/watchlist', 'Watchlist', 'eye', 'canManageDiscordBot'],
];
